### PR TITLE
Add support for Mypy 1.0

### LINKED ISSUE #2515: mypy_plugin not compatible with mypy 1.0.0
I get a traceback from `mypy_plugin.py` after upgrading mypy from 0.991 to 1.0.0:

```
> mypy app --show-traceback
C:\workspace\python\flaskpatient\.venv\Lib\site-packages\strawberry\federation\schema_directives.py:33: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.0.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "mypy\semanal.py", line 6210, in accept
  File "mypy\nodes.py", line 1133, in accept
  File "mypy\semanal.py", line 1545, in visit_class_def
  File "mypy\semanal.py", line 1625, in analyze_class
  File "mypy\semanal.py", line 1652, in analyze_class_body_common
  File "mypy\semanal.py", line 1721, in apply_class_plugin_hooks
  File "C:\workspace\python\flaskpatient\.venv\Lib\site-packages\strawberry\ext\mypy_plugin.py", line 848, in custom_dataclass_class_maker_callback
    transformer.transform()
  File "C:\workspace\python\flaskpatient\.venv\Lib\site-packages\strawberry\ext\mypy_plugin.py", line 578, in transform
    args=[attr.to_argument() for attr in attributes if attr.is_in_init],
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\python\flaskpatient\.venv\Lib\site-packages\strawberry\ext\mypy_plugin.py", line 578, in <listcomp>
    args=[attr.to_argument() for attr in attributes if attr.is_in_init],
          ^^^^^^^^^^^^^^^^^^
TypeError: to_argument() missing required argument 'current_info' (pos 1)
C:\workspace\python\flaskpatient\.venv\Lib\site-packages\strawberry\federation\schema_directives.py:33: : note: use --pdb to drop into pdb
```

## System Information

 - Operating system: Windows 11 22H2
 - Strawberry version: 0.155.4

### PR DESCRIPTION
**Pull request by patrick91**
This PR adds support for Mypy 1.0 by doing a couple of checks in the plugin and updating the tests :)

Closes #2515

### CODE REVIEW

File: strawberry/ext/mypy_plugin.py [hunk 1]
```diff
@@ -1,9 +1,11 @@
 import re
-import warnings
 from decimal import Decimal
 from typing import Any, Callable, Dict, List, Optional, Set, Tuple, Union, cast
 from typing_extensions import Final
 
+from packaging.version import Version
+from packaging.version import parse as parse_version
```
Comment (patrick91) [inline strawberry/ext/mypy_plugin.py:7]: Mypy switched to a a.b.c format now, so I imported this `parse_version` function from packaging, but I'm not convinced we should add a dependency just for this, maybe we can vendorize the function?

What do you think @BryceBeagle @skilkis?

Comment (bellini666) [reply strawberry/ext/mypy_plugin.py:7]: Why not parse the version as a tuple? So `0.991` becomes `(0, 991)` and `1.0.0` becomes `(1, 0, 0)`. Then the comparison below can be done with `version < (0, 93)`

If the versions has any extra non int parts in it (e.g. `0.991.extra`), we could force the first 3 tuple elements to be an int, and fill it with `0`. So that would become `(0, 991, 0, "extra"). And the comparison above would still work correct

Comment (patrick91) [reply strawberry/ext/mypy_plugin.py:7]: that's a good point, I didn't want to write any logic for the parsing (I'm lazy), and reading online it seems to be suggested to use a library like that one :D

Comment (bellini666) [reply strawberry/ext/mypy_plugin.py:7]: I always prefer to not have to reinvent the wheel too :)

Personally I don't have anything against adding that dependency, specially because it is just an extra ~300kb. Maybe some people can look at it as "wow, that's an extra ~300kb, too much" hahaha

Comment (skilkis) [reply strawberry/ext/mypy_plugin.py:7]: Since `packaging` is developed and maintained by PyPA I'm all for it! 🚀 I believe some other projects are still using `pkg_resources` which is discouraged by PyPA themselves, so nice find with `packaging`. I didn't know it existed

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

This release adds support for Mypy 1.0


---
Here's the preview release card for twitter:




Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @patrick91 for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by botberry** [comment]
## Apollo Federation Subgraph Compatibility Results

<table>
<thead>
<tr><th>Federation 1 Support</th><th>Federation 2 Support</th></tr>
</thead>
<tbody>
<tr><td><table><tr><th><code>_service</code></th><td>🟢</td></tr><tr><th><code>@key (single)</code></th><td>🟢</td></tr><tr><th><code>@key (multi)</code></th><td>🟢</td></tr><tr><th><code>@key (composite)</code></th><td>🟢</td></tr><tr><th><code>repeatable @key</code></th><td>🟢</td></tr><tr><th><code>@requires</code></th><td>🟢</td></tr><tr><th><code>@provides</code></th><td>🟢</td></tr><tr><th><code>federated tracing</code></th><td>🔲</td></tr></table></td><td><table><tr><th><code>@link</code></th><td>🟢</td></tr><tr><th><code>@shareable</code></th><td>🟢</td></tr><tr><th><code>@tag</code></th><td>🟢</td></tr><tr><th><code>@override</code></th><td>🟢</td></tr><tr><th><code>@inaccessible</code></th><td>🟢</td></tr></table></td></tr>
</tbody>
</table>

Learn more:
* [Apollo Federation Subgraph Specification](https://www.apollographql.com/docs/federation/subgraph-spec/)
* [Compatibility Tests](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/COMPATIBILITY.md)
