### ISSUE TITLE
Python 3.14 missing mandatory positional argument doc in Field

### ISSUE THREAD

**Issue by ldynia** [strawberry-graphql/strawberry#4269]
## Error

```
TypeError: Field.__init__() missing 1 required positional argument: 'doc'
```

## Problem

The below `if` statement doesn't work in Python 3.14 because `doc` in this version is a positional argument, so it cannot be passed as kwarg.

**strawberry/types/field.py**
```python
# doc was added to python 3.14 and it is required
if sys.version_info >= (3, 14):
    kwargs["doc"] = None

super().__init__(
    default=default,
    default_factory=default_factory,  # type: ignore
    init=is_basic_field,
    repr=is_basic_field,
    compare=is_basic_field,
    hash=None,
    metadata=metadata or {},
    **kwargs,
)
```

## Solution

For Python 3.14 and greater, add doc as a positional argument.

## System Information

 - Operating system: Linux
 - Python version: 3.12
 - Strawberry version (if applicable): Latest (0.307.1)

**Comment by patrick91** [comment]
@ldynia can you post your full stacktrace?

doc is a keyword argument: https://docs.python.org/3/library/dataclasses.html#dataclasses.field

**Comment by ldynia** [comment]
@patrick91 The bug was fund in this project https://github.com/nrbnlulu/strawberry-django-auth/actions/runs/22418983439/job/64947210935

```
task: [test] cd testproject && uv run  migrate.py
warning: The package `pydoc-markdown==4.8.2` does not have an extra named `novella`
Downloading django (8.0MiB)
 Downloaded django
Uninstalled 2 packages in 197ms
Installed 2 packages in 167ms
Traceback (most recent call last):
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/tests/testproject/migrate.py", line 12, in <module>
    execute_from_command_line(args)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/django/core/management/__init__.py", line 383, in execute
    settings.INSTALLED_APPS
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/django/conf/__init__.py", line 75, in __getattr__
    self._setup(name)
    ~~~~~~~~~~~^^^^^^
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/django/conf/__init__.py", line 62, in _setup
    self._wrapped = Settings(settings_module)
                    ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/django/conf/__init__.py", line 162, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/runner/work/_temp/uv-python-dir/cpython-3.14.3-linux-x86_64-gnu/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/tests/testproject/settings.py", line 15, in <module>
    from gqlauth.settings_type import GqlAuthSettings
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/gqlauth/settings_type.py", line 17, in <module>
    from strawberry import ID
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/__init__.py", line 7, in <module>
    from . import experimental, federation, relay
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/federation/__init__.py", line 7, in <module>
    from .schema import Schema
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/federation/schema.py", line 22, in <module>
    from strawberry.schema import Schema as BaseSchema
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/schema/__init__.py", line 2, in <module>
    from .schema import Schema
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/schema/schema.py", line 29, in <module>
    from strawberry import relay
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/relay/__init__.py", line 1, in <module>
    from .fields import ConnectionExtension, NodeExtension, connection, node
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/relay/fields.py", line 49, in <module>
    from .types import Connection, GlobalID, Node, NodeIterableType, NodeType
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/relay/types.py", line 344, in <module>
    class Node:
    ...<273 lines>...
            return next(iter(cast(Iterable[Self], retval)))
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/relay/types.py", line 381, in Node
    @field(name="id", description="The Globally Unique ID of this object")
     ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/types/field.py", line 579, in field
    field_ = StrawberryField(
        python_name=None,
    ...<10 lines>...
        extensions=extensions or [],
    )
  File "/home/runner/work/strawberry-django-auth/strawberry-django-auth/.venv/lib/python3.14/site-packages/strawberry/types/field.py", line 107, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        default=default,
        ^^^^^^^^^^^^^^^^
    ...<6 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
TypeError: Field.__init__() missing 1 required positional argument: 'doc'
task: Failed to run task "test": exit status 1
```

**Comment by patrick91** [comment]
That library probably needs to update the Strawberry version 😊 I'll close this, as it's not a bug on our side 😊
