### PR TITLE
fix(types): pass doc as positional arg for Python 3.14+ compatibility

### LINKED ISSUE #4269: Python 3.14 missing mandatory positional argument doc in Field
## Error

```
TypeError: Field.__init__() missing 1 required positional argument: 'doc'
```

## Problem

The below `if` statement doesn't work in Python 3.14 because `doc` in this version is a positional argument, so it cannot be passed as kwarg.

**strawberry/types/field.py**
```python
# doc was added to python 3.14 and it is required
if sys.version_info >= (3, 14):
    kwargs["doc"] = None

super().__init__(
    default=default,
    default_factory=default_factory,  # type: ignore
    init=is_basic_field,
    repr=is_basic_field,
    compare=is_basic_field,
    hash=None,
    metadata=metadata or {},
    **kwargs,
)
```

## Solution

For Python 3.14 and greater, add doc as a positional argument.

## System Information

 - Operating system: Linux
 - Python version: 3.12
 - Strawberry version (if applicable): Latest (0.307.1)

### PR DESCRIPTION
**Pull request by armorbreak001**
In Python 3.14, `dataclasses.Field.__init__` gained a required `doc` positional parameter (PEP 749). The current code attempts to pass it via `**kwargs`, which raises `TypeError: Field.__init__() missing 1 required positional argument: doc` because the parameter cannot be accepted as a keyword argument.

**Change:** Pass `doc=None` explicitly as a positional argument in the `super().__init__()` call when running on Python 3.14+, instead of adding it to `kwargs`.

Fixes #4269

## Summary by Sourcery

Bug Fixes:
- Fix Field.__init__ calls on Python 3.14+ by passing the required doc parameter positionally instead of via kwargs.

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to this project!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
---
release type: patch
---

Description of the changes, ideally with some examples, if adding a new feature.

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)
```

**Comment by bellini666** [comment]
Hi @armorbreak001 ,

As @patrick91 mentioned on https://github.com/strawberry-graphql/strawberry/issues/4269, `doc` can be passed as a keyword, and the issue reported is in the other library.

Going to close this as we are not going to fix it this way. But please, feel free to open more PRs for other contributions! :)
