### ISSUE TITLE
0.65.4 – possible breaking change – "partially initialized module 'strawberry' has no attribute 'type'" (circular import?)

### ISSUE THREAD

**Issue by 2malh** [strawberry-graphql/strawberry#1017]
Hey, upgrading to 0.65.4 throws me the following error:
```py
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/venv/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/venv/lib/python3.9/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/venv/lib/python3.9/site-packages/strawberry/__init__.py", line 1, in <module>
    from . import django, experimental, federation
  File "/venv/lib/python3.9/site-packages/strawberry/django/__init__.py", line 4, in <module>
    from strawberry_django import *  # type: ignore # noqa: F401, F403
  File "/venv/lib/python3.9/site-packages/strawberry_django/__init__.py", line 1, in <module>
    from . import auth, filters, ordering
  File "/venv/lib/python3.9/site-packages/strawberry_django/filters.py", line 9, in <module>
    from .fields.types import is_auto
  File "/venv/lib/python3.9/site-packages/strawberry_django/fields/types.py", line 13, in <module>
    @strawberry.type
AttributeError: partially initialized module 'strawberry' has no attribute 'type' (most likely due to a circular import)
```

Downgrading back to 0.65.3 resolved this issue for me.

I take usage of the strawberry.django package, include auto from it and use the strawberry.django.type and field definitions

**Comment by BryceBeagle** [comment]
Something must have broken in #994. @la4de any ideas?

**Comment by sky-code** [comment]
Have the same problem with 0.65.4

**Comment by la4de** [comment]
I propose to revert my previous change. See PR #1019. We need to find out better solution for symbol resolution issue with IDEs.

**Comment by la4de** [comment]
Workaround is to use 0.65.3

**Comment by marcoacierno** [comment]
We merged and released a fix for this.

Closing this, let us know if it still an issue with recent Strawberry versions.
