### ISSUE TITLE
mypy_plugin not compatible with mypy 1.0.0

### ISSUE THREAD

**Issue by juergenzimmermann** [strawberry-graphql/strawberry#2515]
I get a traceback from `mypy_plugin.py` after upgrading mypy from 0.991 to 1.0.0:

```
> mypy app --show-traceback
C:\workspace\python\flaskpatient\.venv\Lib\site-packages\strawberry\federation\schema_directives.py:33: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.0.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "mypy\semanal.py", line 6210, in accept
  File "mypy\nodes.py", line 1133, in accept
  File "mypy\semanal.py", line 1545, in visit_class_def
  File "mypy\semanal.py", line 1625, in analyze_class
  File "mypy\semanal.py", line 1652, in analyze_class_body_common
  File "mypy\semanal.py", line 1721, in apply_class_plugin_hooks
  File "C:\workspace\python\flaskpatient\.venv\Lib\site-packages\strawberry\ext\mypy_plugin.py", line 848, in custom_dataclass_class_maker_callback
    transformer.transform()
  File "C:\workspace\python\flaskpatient\.venv\Lib\site-packages\strawberry\ext\mypy_plugin.py", line 578, in transform
    args=[attr.to_argument() for attr in attributes if attr.is_in_init],
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\python\flaskpatient\.venv\Lib\site-packages\strawberry\ext\mypy_plugin.py", line 578, in <listcomp>
    args=[attr.to_argument() for attr in attributes if attr.is_in_init],
          ^^^^^^^^^^^^^^^^^^
TypeError: to_argument() missing required argument 'current_info' (pos 1)
C:\workspace\python\flaskpatient\.venv\Lib\site-packages\strawberry\federation\schema_directives.py:33: : note: use --pdb to drop into pdb
```

## System Information

 - Operating system: Windows 11 22H2
 - Strawberry version: 0.155.4

**Comment by Hazealign** [comment]
Same Error in macOS 13.2 (arm64).
