### ISSUE TITLE
Fail to resolve string type hint

### ISSUE THREAD

**Issue by fabien-michel** [strawberry-graphql/strawberry#2368]
When using string type annotation to avoid circular reference, it fail to resolve with `AttributeError: module 'path.to.module' has no attribute 'types'`. Where `types` is a module containing `strawberry.type` things

Not sure if it is a bug or a misuse but this was working with strawberry `0.140`.

## Describe the Bug

Have this directory structure:
```
path/to/module/:
  - schema.py
  - types/:
    - __init__.py
    - first_type.py
    - second_type.py
```
**schema.py**
```python
from .types
@strawberry.type
class Query:
    first: FirstType = None
```

**types/__init__.py**
```python
from .first_type import FirstType
from .second_type import SecondType
```

**types/first_type.py**
```python
from typing import Optional
import strawberry
import path.to.module.types

@strawberry.type
class FirstType:
    first: "Optional[path.to.module.types.SecondType]"
```

**types/second_type.py**
```python
from typing import Optional
import strawberry
import path.to.module.types

@strawberry.type
class SecondType:
    second: "Optional[path.to.module.types.FirstType]"
```

Error returned at schema initialization: `AttributeError: module 'path.to.module' has no attribute 'types'`

## System Information

 - Operating system: Linux
 - Strawberry version (if applicable): 0.142.3

## Additional Context

Diff of updated django tests in order to reproduce:
[diff.txt](https://github.com/strawberry-graphql/strawberry/files/10123976/diff.txt)
